[package]
name = "storageengine_rocksdb"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "storageengine_rocksdb"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.29.1"
rocksdb = "0.21.0"
